version: '3.4'

services:
  minio:
    container_name: portfolio_minio
    image: minio/minio:RELEASE.2021-09-15T04-54-25Z.hotfix.908b0f10a
    environment:
      MINIO_ROOT_USER: AccessKey
      MINIO_ROOT_PASSWORD: SecretKey
    command: server --console-address ":9001" /data
    volumes:
      - ./docker/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
