version: '3.4'

services:

  portfolio.api:
    image: ${DOCKER_REGISTRY-}portfolio_api
    build:
      context: .
      dockerfile: src/Web/Portfolio.Web/Dockerfile
    container_name: portfolio.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnectionString=User ID=portfolio;Password=portfolio;Host=portfolio_postgres;Port=5432;Database=Portfolio.Backend;Pooling=true;
      - S3__ServiceUrl=http://portfolio_minio:9000
      - Rabbit__Url=amqp://guest:guest@rabbit:5672/
    depends_on:
      - portfolio.postgres
      - portfolio.minio
      - portfolio.rabbitmq
    ports:
      - "8000:80"

  portfolio.postgres:
    container_name: portfolio_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
      POSTGRES_DB: "Portfolio.Backend"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    expose:
      - "5433"
    ports:
      - "5433:5432"

  portfolio.minio:
    container_name: portfolio_minio
    image: minio/minio:RELEASE.2021-09-15T04-54-25Z.hotfix.908b0f10a
    environment:
      MINIO_ROOT_USER: AccessKey
      MINIO_ROOT_PASSWORD: SecretKey
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  portfolio.rabbitmq:
    container_name: portfolio_rabbitmq
    hostname: rabbit
    image: rabbitmq:3.8-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  minio_data:
  postgres_data:

